const name = '@CANDIDATE'

export default {
  LINKEDIN_DATA_REQUEST: `${name}/LINKEDIN_DATA_REQUEST`,
  SET_OBTAINED_USER_DATA_FROM_LINKEDIN: `${name}/SET_OBTAINED_USER_DATA_FROM_LINKEDIN`,
  SET_FORM_DATA: `${name}/SET_FORM_DATA`,
}
